### ISSUE TITLE
Заменить статичные страницы на модуль pages

### ISSUE THREAD

**Issue by alexbarmin** [ASUPortal/ASUPortalPHP#15]
На портале полно статичных страниц, например, "Ссылки". Их содержимое зашито прямо в коде. Считаю, что содержимое нужно достать и сделать как обычные страницы в модуле pages, а файлы убить даже из репозитория.

**Comment by alexbarmin** [comment]
Господа, отпишитесь, если это сделано - я закрою тикет.

**Comment by ASUPortal** [comment]
Закрывай
