### ISSUE TITLE
Сортировка новостей

### ISSUE THREAD

**Issue by alexbarmin** [ASUPortal/ASUPortalPHP#43]
Новости сортируются по дням (сначала новые, потом старые) и, почему-то, внутри дней (сначала старые, потом новые).

Полагаю, нужно сделать, чтобы всегда отображались сначала новые, потом старые. 
С другой стороны, есть новый модуль новостей, который не используется. Возможно, стоит заменить старые новости на новые.

**Comment by startsevgena** [comment]
И уже классификацию народ просит. Лента быстро убегает.

**Comment by alexbarmin** [comment]
Надо взять и старые новости новыми заменить - там модуль готов и я не помню, почему его не использую.

**Comment by alexbarmin** [comment]
Апну тему. 
Кстати, полностью убилась мобильная тема. Предлагаю ее, все-таки, восстановить. Тем более, jQuery Mobile - наше все.
